---
id: ElasticSearch
name: ElasticSearch
full: ElasticSearch client library
description: A lightweight library for ElasticSearch (http://www.elasticsearch.org/).
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_ElasticSearch
authors:
  - name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  - name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 2.0.0
  api: 2.0.0alpha1
state:
  release: stable
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7 || ^8
    composer:
      horde/exception: ^3
      horde/http: ^3
vendor: horde
keywords: null
ci-platform:
  '8.0':
    - php: ^7.4 || ^8
    - ext-dom
  '8.1':
    - php: ^7.4 || ^8
    - ext-dom
  '8.2':
    - php: ^7.4 || ^8
    - ext-dom
  '8.3':
    - php: ^7.4 || ^8
    - ext-dom
  '8.4':
    - php: ^7.4 || ^8
    - ext-dom
  '8.5':
    - php: ^7.4 || ^8
    - ext-dom
  '8.6':
    - php: ^7.4 || ^8
    - ext-dom
ci-platform-flags:
  needs_installer_plugin: false
